"""TypeScript type generation from loader return type hints."""

from __future__ import annotations

import typing
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from taiyaki_web.app import Taiyaki

_TYPE_MAP: dict[type, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
    type(None): "null",
}


def _py_type_to_ts(py_type: Any) -> str:
    """Convert a Python type annotation to a TypeScript type string."""
    # Direct mapping
    if py_type in _TYPE_MAP:
        return _TYPE_MAP[py_type]

    # Handle typing generics
    origin = getattr(py_type, "__origin__", None)

    # Optional[X] → X | null
    if origin is typing.Union:
        args = py_type.__args__
        ts_parts = [_py_type_to_ts(a) for a in args]
        return " | ".join(ts_parts)

    # list[X] → Array<X>
    if origin is list:
        args = getattr(py_type, "__args__", None)
        if args:
            return f"Array<{_py_type_to_ts(args[0])}>"
        return "Array<unknown>"

    # dict[K, V] → Record<K, V>
    if origin is dict:
        args = getattr(py_type, "__args__", None)
        if args and len(args) == 2:
            return f"Record<{_py_type_to_ts(args[0])}, {_py_type_to_ts(args[1])}>"
        return "Record<string, unknown>"

    # tuple[X, Y] → [X, Y]
    if origin is tuple:
        args = getattr(py_type, "__args__", None)
        if args:
            return f"[{', '.join(_py_type_to_ts(a) for a in args)}]"
        return "unknown[]"

    # TypedDict — has __annotations__
    if hasattr(py_type, "__annotations__") and hasattr(py_type, "__required_keys__"):
        return py_type.__name__

    # Fallback
    if isinstance(py_type, type):
        name = py_type.__name__
        if name in ("str", "int", "float", "bool"):
            return _TYPE_MAP.get(py_type, "unknown")
        return "unknown"

    return "unknown"


def _generate_typed_dict_interface(td: type) -> str:
    """Generate a TypeScript interface from a TypedDict class."""
    lines = [f"export interface {td.__name__} {{"]
    hints = typing.get_type_hints(td)
    required = getattr(td, "__required_keys__", set())
    for field_name, field_type in hints.items():
        ts_type = _py_type_to_ts(field_type)
        optional = "?" if field_name not in required else ""
        lines.append(f"  {field_name}{optional}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def generate_types(app: Taiyaki) -> str:
    """Generate TypeScript type definitions from app route metadata."""
    output_parts: list[str] = [
        "// Auto-generated by dark typegen",
        "// Do not edit manually",
        "",
    ]

    seen_typedicts: set[str] = set()

    for meta in app._route_meta:
        component = meta.get("component")
        loader = meta.get("loader")
        if not component or not loader:
            continue

        try:
            hints = typing.get_type_hints(loader)
        except Exception:
            continue

        return_type = hints.get("return")
        if return_type is None:
            continue

        # Check if return type is a TypedDict
        if hasattr(return_type, "__annotations__") and hasattr(
            return_type, "__required_keys__"
        ):
            if return_type.__name__ not in seen_typedicts:
                seen_typedicts.add(return_type.__name__)
                output_parts.append(_generate_typed_dict_interface(return_type))
                output_parts.append("")
            output_parts.append(
                f"export type {component}Props = {return_type.__name__};"
            )
        elif return_type is dict or getattr(return_type, "__origin__", None) is dict:
            output_parts.append(
                f"export type {component}Props = Record<string, unknown>;"
            )
        else:
            ts_type = _py_type_to_ts(return_type)
            output_parts.append(f"export type {component}Props = {ts_type};")

        output_parts.append("")

    return "\n".join(output_parts)
