#ifndef TAIYAKI_H
#define TAIYAKI_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

typedef enum taiyaki_type {
  LIBTS_TYPE_UNDEFINED = 0,
  LIBTS_TYPE_NULL = 1,
  LIBTS_TYPE_BOOL = 2,
  LIBTS_TYPE_NUMBER = 3,
  LIBTS_TYPE_STRING = 4,
  LIBTS_TYPE_OBJECT = 5,
  LIBTS_TYPE_ARRAY = 6,
  LIBTS_TYPE_FUNCTION = 7,
} taiyaki_type;

typedef struct taiyaki_runtime taiyaki_runtime;

typedef struct taiyaki_value taiyaki_value;

/**
 * C callback type for host functions.
 */
typedef struct taiyaki_value *(*LibtsHostFn)(const struct taiyaki_value *const *args,
                                           uintptr_t argc,
                                           void *user_data);

/**
 * Returns the last error message, or NULL if no error.
 * The returned pointer is valid until the next libts call.
 */
const char *taiyaki_get_last_error(void);

/**
 * Creates a new runtime. Returns NULL on failure.
 */
struct taiyaki_runtime *taiyaki_runtime_new(void);

/**
 * Frees a runtime. NULL-safe.
 */
void taiyaki_runtime_free(struct taiyaki_runtime *rt);

/**
 * Evaluates JavaScript code.
 * `code` is a UTF-8 string of length `len` (no NUL terminator required).
 * Returns a pointer to LibtsValue on success (caller frees with taiyaki_value_free).
 * Returns NULL on failure.
 */
struct taiyaki_value *taiyaki_eval(struct taiyaki_runtime *rt, const char *code, uintptr_t len);

/**
 * Evaluates TypeScript code (strips type annotations before execution).
 * `code` is a UTF-8 string of length `len`.
 */
struct taiyaki_value *taiyaki_eval_ts(struct taiyaki_runtime *rt, const char *code, uintptr_t len);

/**
 * Returns the type of a value.
 */
enum taiyaki_type taiyaki_value_type(const struct taiyaki_value *val);

/**
 * Returns the value as a number. Returns 0.0 if not a number.
 */
double taiyaki_value_as_number(const struct taiyaki_value *val);

/**
 * Returns the value as a boolean (1 or 0). Returns 0 if not a boolean.
 */
int32_t taiyaki_value_as_bool(const struct taiyaki_value *val);

/**
 * Returns the value as a string.
 * The returned pointer is valid until the next taiyaki_value_as_string call
 * on the same value, or until taiyaki_value_free.
 * If `out_len` is non-NULL, writes the string length.
 * Returns NULL if not a string.
 */
const char *taiyaki_value_as_string(struct taiyaki_value *val, uintptr_t *out_len);

/**
 * Frees a LibtsValue. NULL-safe.
 * For handle values, also releases the engine-side handle.
 */
void taiyaki_value_free(struct taiyaki_value *val);

/**
 * Creates an f64 value.
 */
struct taiyaki_value *taiyaki_value_number(double n);

/**
 * Creates a string value. `s` is a UTF-8 string of length `len`.
 */
struct taiyaki_value *taiyaki_value_string(const char *s, uintptr_t len);

/**
 * Creates a boolean value. 0 maps to false, anything else to true.
 */
struct taiyaki_value *taiyaki_value_bool(int32_t b);

/**
 * Creates a null value.
 */
struct taiyaki_value *taiyaki_value_null(void);

/**
 * Creates an undefined value.
 */
struct taiyaki_value *taiyaki_value_undefined(void);

/**
 * Creates an empty JS object.
 */
struct taiyaki_value *taiyaki_object_new(struct taiyaki_runtime *rt);

/**
 * Sets a property on an object. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_object_set(struct taiyaki_runtime *rt,
                         const struct taiyaki_value *obj,
                         const char *key,
                         uintptr_t key_len,
                         const struct taiyaki_value *val);

/**
 * Gets a property from an object.
 */
struct taiyaki_value *taiyaki_object_get(struct taiyaki_runtime *rt,
                                     const struct taiyaki_value *obj,
                                     const char *key,
                                     uintptr_t key_len);

/**
 * Creates an empty JS array.
 */
struct taiyaki_value *taiyaki_array_new(struct taiyaki_runtime *rt);

/**
 * Pushes an element onto an array. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_array_push(struct taiyaki_runtime *rt,
                         const struct taiyaki_value *arr,
                         const struct taiyaki_value *val);

/**
 * Gets an element from an array by index.
 */
struct taiyaki_value *taiyaki_array_get(struct taiyaki_runtime *rt,
                                    const struct taiyaki_value *arr,
                                    uint32_t index);

/**
 * Returns the length of an array. Returns -1 on error.
 */
int32_t taiyaki_array_length(struct taiyaki_runtime *rt, const struct taiyaki_value *arr);

/**
 * Calls a JS function. `func` must be a FunctionHandle.
 */
struct taiyaki_value *taiyaki_call(struct taiyaki_runtime *rt,
                               const struct taiyaki_value *func,
                               const struct taiyaki_value *const *args,
                               uintptr_t argc);

/**
 * Serializes a handle value to a JSON string.
 * Returns a String-typed LibtsValue.
 */
struct taiyaki_value *taiyaki_to_json(struct taiyaki_runtime *rt, const struct taiyaki_value *val);

/**
 * Parses a JSON string and returns a handle value.
 */
struct taiyaki_value *taiyaki_from_json(struct taiyaki_runtime *rt, const char *json, uintptr_t len);

/**
 * Registers a host function as a JS global. Returns 0 on success, -1 on error.
 * `name` is a UTF-8 string of length `name_len`.
 * `callback` is a C function pointer; `user_data` is passed through to the callback.
 */
int32_t taiyaki_register_fn(struct taiyaki_runtime *rt,
                          const char *name,
                          uintptr_t name_len,
                          LibtsHostFn callback,
                          void *user_data);

#endif  /* TAIYAKI_H */
