#ifndef TAIYAKI_H
#define TAIYAKI_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

typedef enum LibtsType {
  LIBTS_TYPE_UNDEFINED = 0,
  LIBTS_TYPE_NULL = 1,
  LIBTS_TYPE_BOOL = 2,
  LIBTS_TYPE_NUMBER = 3,
  LIBTS_TYPE_STRING = 4,
  LIBTS_TYPE_OBJECT = 5,
  LIBTS_TYPE_ARRAY = 6,
  LIBTS_TYPE_FUNCTION = 7,
} LibtsType;

typedef struct LibtsRuntime LibtsRuntime;

typedef struct LibtsValue LibtsValue;

typedef struct Option_JSObjectCallAsFunctionCallback Option_JSObjectCallAsFunctionCallback;

typedef struct Option_JSObjectFinalizeCallback Option_JSObjectFinalizeCallback;

typedef struct Option_JSShouldTerminateCallback Option_JSShouldTerminateCallback;

typedef void *JSGlobalContextRef;

typedef void *JSClassRef;

typedef void *JSObjectRef;

typedef const void *JSContextRef;

typedef const void *JSContextGroupRef;

typedef uint32_t JSType;

typedef const void *JSValueRef;

typedef void *JSStringRef;

/**
 * Callback invoked when a JSC object created with a custom class is called as a function.
 */
typedef JSValueRef (*JSObjectCallAsFunctionCallback)(JSContextRef ctx,
                                                     JSObjectRef function,
                                                     JSObjectRef this_object,
                                                     uintptr_t argument_count,
                                                     const JSValueRef *arguments,
                                                     JSValueRef *exception);

typedef uint32_t JSPropertyAttributes;

typedef uint32_t JSClassAttributes;

/**
 * Matches the C struct layout of JSClassDefinition.
 */
typedef struct JSClassDefinition {
  int32_t version;
  JSClassAttributes attributes;
  const char *class_name;
  JSClassRef parent_class;
  const void *static_values;
  const void *static_functions;
  const void *initialize;
  struct Option_JSObjectFinalizeCallback finalize;
  const void *has_property;
  const void *get_property;
  const void *set_property;
  const void *delete_property;
  const void *get_property_names;
  struct Option_JSObjectCallAsFunctionCallback call_as_function;
  const void *call_as_constructor;
  const void *has_instance;
  const void *convert_to_type;
} JSClassDefinition;

/**
 * C callback type for host functions.
 */
typedef struct LibtsValue *(*LibtsHostFn)(const struct LibtsValue *const *args,
                                          uintptr_t argc,
                                          void *user_data);

/**
 * Memory usage statistics.
 */
typedef struct taiyaki_memory_stats {
  int64_t malloc_size;
  int64_t memory_used_size;
  int64_t atom_count;
  int64_t str_count;
  int64_t obj_count;
  int64_t prop_count;
  int64_t js_func_count;
  int64_t c_func_count;
  int64_t array_count;
} taiyaki_memory_stats;

extern JSGlobalContextRef JSGlobalContextCreate(JSClassRef global_object_class);

extern void JSGlobalContextRelease(JSGlobalContextRef ctx);

extern JSObjectRef JSContextGetGlobalObject(JSContextRef ctx);

extern JSContextGroupRef JSContextGetGroup(JSContextRef ctx);

extern JSType JSValueGetType(JSContextRef ctx, JSValueRef value);

extern bool JSValueIsUndefined(JSContextRef ctx, JSValueRef value);

extern bool JSValueIsNull(JSContextRef ctx, JSValueRef value);

extern bool JSValueIsBoolean(JSContextRef ctx, JSValueRef value);

extern bool JSValueIsNumber(JSContextRef ctx, JSValueRef value);

extern bool JSValueIsString(JSContextRef ctx, JSValueRef value);

extern bool JSValueIsObject(JSContextRef ctx, JSValueRef value);

extern bool JSValueIsArray(JSContextRef ctx, JSValueRef value);

extern JSValueRef JSValueMakeUndefined(JSContextRef ctx);

extern JSValueRef JSValueMakeNull(JSContextRef ctx);

extern JSValueRef JSValueMakeBoolean(JSContextRef ctx, bool value);

extern JSValueRef JSValueMakeNumber(JSContextRef ctx, double value);

extern JSValueRef JSValueMakeString(JSContextRef ctx, JSStringRef string);

extern bool JSValueToBoolean(JSContextRef ctx, JSValueRef value);

extern double JSValueToNumber(JSContextRef ctx, JSValueRef value, JSValueRef *exception);

extern JSStringRef JSValueToStringCopy(JSContextRef ctx, JSValueRef value, JSValueRef *exception);

extern JSObjectRef JSValueToObject(JSContextRef ctx, JSValueRef value, JSValueRef *exception);

extern void JSValueProtect(JSContextRef ctx, JSValueRef value);

extern void JSValueUnprotect(JSContextRef ctx, JSValueRef value);

extern JSValueRef JSValueMakeFromJSONString(JSContextRef ctx, JSStringRef string);

extern JSStringRef JSValueCreateJSONString(JSContextRef ctx,
                                           JSValueRef value,
                                           uint32_t indent,
                                           JSValueRef *exception);

extern JSStringRef JSStringCreateWithUTF8CString(const char *string);

extern void JSStringRelease(JSStringRef string);

extern uintptr_t JSStringGetMaximumUTF8CStringSize(JSStringRef string);

extern uintptr_t JSStringGetUTF8CString(JSStringRef string, char *buffer, uintptr_t buffer_size);

extern JSObjectRef JSObjectMake(JSContextRef ctx, JSClassRef js_class, void *data);

extern JSObjectRef JSObjectMakeFunctionWithCallback(JSContextRef ctx,
                                                    JSStringRef name,
                                                    JSObjectCallAsFunctionCallback callback);

extern JSObjectRef JSObjectMakeArray(JSContextRef ctx,
                                     uintptr_t argument_count,
                                     const JSValueRef *arguments,
                                     JSValueRef *exception);

extern JSValueRef JSObjectGetProperty(JSContextRef ctx,
                                      JSObjectRef object,
                                      JSStringRef property_name,
                                      JSValueRef *exception);

extern void JSObjectSetProperty(JSContextRef ctx,
                                JSObjectRef object,
                                JSStringRef property_name,
                                JSValueRef value,
                                JSPropertyAttributes attributes,
                                JSValueRef *exception);

extern JSValueRef JSObjectGetPropertyAtIndex(JSContextRef ctx,
                                             JSObjectRef object,
                                             uint32_t property_index,
                                             JSValueRef *exception);

extern void JSObjectSetPropertyAtIndex(JSContextRef ctx,
                                       JSObjectRef object,
                                       uint32_t property_index,
                                       JSValueRef value,
                                       JSValueRef *exception);

extern JSValueRef JSObjectCallAsFunction(JSContextRef ctx,
                                         JSObjectRef object,
                                         JSObjectRef this_object,
                                         uintptr_t argument_count,
                                         const JSValueRef *arguments,
                                         JSValueRef *exception);

extern bool JSObjectIsFunction(JSContextRef ctx, JSObjectRef object);

extern void *JSObjectGetPrivate(JSObjectRef object);

extern bool JSObjectSetPrivate(JSObjectRef object, void *data);

extern JSClassRef JSClassCreate(const struct JSClassDefinition *definition);

extern void JSClassRelease(JSClassRef js_class);

extern JSValueRef JSEvaluateScript(JSContextRef ctx,
                                   JSStringRef script,
                                   JSObjectRef this_object,
                                   JSStringRef source_url,
                                   int32_t starting_line_number,
                                   JSValueRef *exception);

extern void JSGarbageCollect(JSContextRef ctx);

extern void JSContextGroupSetExecutionTimeLimit(JSContextGroupRef group,
                                                double limit,
                                                struct Option_JSShouldTerminateCallback callback,
                                                void *context);

extern void JSContextGroupClearExecutionTimeLimit(JSContextGroupRef group);

extern JSObjectRef JSObjectMakeDeferredPromise(JSContextRef ctx,
                                               JSObjectRef *resolve,
                                               JSObjectRef *reject,
                                               JSValueRef *exception);

/**
 * Returns the last error message, or NULL if no error.
 * The returned pointer is valid until the next taiyaki call.
 */
const char *taiyaki_get_last_error(void);

/**
 * Creates a new runtime. Returns NULL on failure.
 */
struct LibtsRuntime *taiyaki_runtime_new(void);

/**
 * Frees a runtime. NULL-safe.
 */
void taiyaki_runtime_free(struct LibtsRuntime *rt);

/**
 * Evaluates JavaScript code.
 * `code` is a UTF-8 string of length `len` (no NUL terminator required).
 * Returns a pointer to LibtsValue on success (caller frees with taiyaki_value_free).
 * Returns NULL on failure.
 */
struct LibtsValue *taiyaki_eval(struct LibtsRuntime *rt, const char *code, uintptr_t len);

/**
 * Evaluates TypeScript code (strips type annotations before execution).
 * `code` is a UTF-8 string of length `len`.
 */
struct LibtsValue *taiyaki_eval_ts(struct LibtsRuntime *rt, const char *code, uintptr_t len);

/**
 * Returns the type of a value.
 */
enum LibtsType taiyaki_value_type(const struct LibtsValue *val);

/**
 * Returns the value as a number. Returns 0.0 if not a number.
 */
double taiyaki_value_as_number(const struct LibtsValue *val);

/**
 * Returns the value as a boolean (1 or 0). Returns 0 if not a boolean.
 */
int32_t taiyaki_value_as_bool(const struct LibtsValue *val);

/**
 * Returns the value as a string.
 * The returned pointer is valid until the next taiyaki_value_as_string call
 * on the same value, or until taiyaki_value_free.
 * If `out_len` is non-NULL, writes the string length.
 * Returns NULL if not a string.
 */
const char *taiyaki_value_as_string(struct LibtsValue *val, uintptr_t *out_len);

/**
 * Frees a LibtsValue. NULL-safe.
 * For handle values, also releases the engine-side handle.
 */
void taiyaki_value_free(struct LibtsValue *val);

/**
 * Creates an f64 value.
 */
struct LibtsValue *taiyaki_value_number(double n);

/**
 * Creates a string value. `s` is a UTF-8 string of length `len`.
 */
struct LibtsValue *taiyaki_value_string(const char *s, uintptr_t len);

/**
 * Creates a boolean value. 0 maps to false, anything else to true.
 */
struct LibtsValue *taiyaki_value_bool(int32_t b);

/**
 * Creates a null value.
 */
struct LibtsValue *taiyaki_value_null(void);

/**
 * Creates an undefined value.
 */
struct LibtsValue *taiyaki_value_undefined(void);

/**
 * Creates an empty JS object.
 */
struct LibtsValue *taiyaki_object_new(struct LibtsRuntime *rt);

/**
 * Sets a property on an object. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_object_set(struct LibtsRuntime *rt,
                           const struct LibtsValue *obj,
                           const char *key,
                           uintptr_t key_len,
                           const struct LibtsValue *val);

/**
 * Gets a property from an object.
 */
struct LibtsValue *taiyaki_object_get(struct LibtsRuntime *rt,
                                      const struct LibtsValue *obj,
                                      const char *key,
                                      uintptr_t key_len);

/**
 * Creates an empty JS array.
 */
struct LibtsValue *taiyaki_array_new(struct LibtsRuntime *rt);

/**
 * Pushes an element onto an array. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_array_push(struct LibtsRuntime *rt,
                           const struct LibtsValue *arr,
                           const struct LibtsValue *val);

/**
 * Gets an element from an array by index.
 */
struct LibtsValue *taiyaki_array_get(struct LibtsRuntime *rt,
                                     const struct LibtsValue *arr,
                                     uint32_t index);

/**
 * Returns the length of an array. Returns -1 on error.
 */
int32_t taiyaki_array_length(struct LibtsRuntime *rt, const struct LibtsValue *arr);

/**
 * Calls a JS function. `func` must be a FunctionHandle.
 */
struct LibtsValue *taiyaki_call(struct LibtsRuntime *rt,
                                const struct LibtsValue *func,
                                const struct LibtsValue *const *args,
                                uintptr_t argc);

/**
 * Serializes a handle value to a JSON string.
 * Returns a String-typed LibtsValue.
 */
struct LibtsValue *taiyaki_to_json(struct LibtsRuntime *rt, const struct LibtsValue *val);

/**
 * Parses a JSON string and returns a handle value.
 */
struct LibtsValue *taiyaki_from_json(struct LibtsRuntime *rt, const char *json, uintptr_t len);

/**
 * Registers a host function as a JS global. Returns 0 on success, -1 on error.
 * `name` is a UTF-8 string of length `name_len`.
 * `callback` is a C function pointer; `user_data` is passed through to the callback.
 */
int32_t taiyaki_register_fn(struct LibtsRuntime *rt,
                            const char *name,
                            uintptr_t name_len,
                            LibtsHostFn callback,
                            void *user_data);

/**
 * Sets the memory limit in bytes. 0 means unlimited.
 */
void taiyaki_set_memory_limit(struct LibtsRuntime *rt, uintptr_t bytes);

/**
 * Sets the maximum stack size in bytes.
 */
void taiyaki_set_max_stack_size(struct LibtsRuntime *rt, uintptr_t bytes);

/**
 * Sets an execution timeout in milliseconds. Uses the interrupt handler.
 */
void taiyaki_set_execution_timeout(struct LibtsRuntime *rt, uint64_t milliseconds);

/**
 * Returns memory usage statistics. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_memory_usage(struct LibtsRuntime *rt, struct taiyaki_memory_stats *out);

/**
 * Triggers garbage collection.
 */
void taiyaki_run_gc(struct LibtsRuntime *rt);

/**
 * Evaluates JavaScript code as an ES module.
 * Returns an ObjectHandle to the module namespace (exports).
 * `code` is a UTF-8 string of length `code_len`.
 * `name` is a UTF-8 module name of length `name_len`.
 */
struct LibtsValue *taiyaki_eval_module(struct LibtsRuntime *rt,
                                       const char *code,
                                       uintptr_t code_len,
                                       const char *name,
                                       uintptr_t name_len);

/**
 * Evaluates TypeScript code as an ES module (strips types first).
 */
struct LibtsValue *taiyaki_eval_module_ts(struct LibtsRuntime *rt,
                                          const char *code,
                                          uintptr_t code_len,
                                          const char *name,
                                          uintptr_t name_len);

/**
 * Registers a module source for later import. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_register_module(struct LibtsRuntime *rt,
                                const char *name,
                                uintptr_t name_len,
                                const char *code,
                                uintptr_t code_len);

#endif  /* TAIYAKI_H */
