#ifndef TAIYAKI_H
#define TAIYAKI_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

typedef enum LibtsType {
  LIBTS_TYPE_UNDEFINED = 0,
  LIBTS_TYPE_NULL = 1,
  LIBTS_TYPE_BOOL = 2,
  LIBTS_TYPE_NUMBER = 3,
  LIBTS_TYPE_STRING = 4,
  LIBTS_TYPE_OBJECT = 5,
  LIBTS_TYPE_ARRAY = 6,
  LIBTS_TYPE_FUNCTION = 7,
} LibtsType;

typedef struct LibtsRuntime LibtsRuntime;

typedef struct LibtsValue LibtsValue;

/**
 * C callback type for host functions.
 */
typedef struct LibtsValue *(*LibtsHostFn)(const struct LibtsValue *const *args,
                                          uintptr_t argc,
                                          void *user_data);

/**
 * Memory usage statistics.
 */
typedef struct taiyaki_memory_stats {
  int64_t malloc_size;
  int64_t memory_used_size;
  int64_t atom_count;
  int64_t str_count;
  int64_t obj_count;
  int64_t prop_count;
  int64_t js_func_count;
  int64_t c_func_count;
  int64_t array_count;
} taiyaki_memory_stats;

/**
 * C callback type for fast f64 native functions (used by AOT wrappers).
 */
typedef double (*TaiyakiFastFnF64)(const double *args, uintptr_t argc, void *user_data);
















































/**
 * Returns the last error message, or NULL if no error.
 * The returned pointer is valid until the next taiyaki call.
 */
const char *taiyaki_get_last_error(void);

/**
 * Creates a new runtime. Returns NULL on failure.
 */
struct LibtsRuntime *taiyaki_runtime_new(void);

/**
 * Frees a runtime. NULL-safe.
 */
void taiyaki_runtime_free(struct LibtsRuntime *rt);

/**
 * Evaluates JavaScript code.
 * `code` is a UTF-8 string of length `len` (no NUL terminator required).
 * Returns a pointer to LibtsValue on success (caller frees with taiyaki_value_free).
 * Returns NULL on failure.
 */
struct LibtsValue *taiyaki_eval(struct LibtsRuntime *rt, const char *code, uintptr_t len);

/**
 * Evaluates TypeScript code (strips type annotations before execution).
 * `code` is a UTF-8 string of length `len`.
 */
struct LibtsValue *taiyaki_eval_ts(struct LibtsRuntime *rt, const char *code, uintptr_t len);

/**
 * Returns the type of a value.
 */
enum LibtsType taiyaki_value_type(const struct LibtsValue *val);

/**
 * Returns the value as a number. Returns 0.0 if not a number.
 */
double taiyaki_value_as_number(const struct LibtsValue *val);

/**
 * Returns the value as a boolean (1 or 0). Returns 0 if not a boolean.
 */
int32_t taiyaki_value_as_bool(const struct LibtsValue *val);

/**
 * Returns the value as a string.
 * The returned pointer is valid until the next taiyaki_value_as_string call
 * on the same value, or until taiyaki_value_free.
 * If `out_len` is non-NULL, writes the string length.
 * Returns NULL if not a string.
 */
const char *taiyaki_value_as_string(struct LibtsValue *val, uintptr_t *out_len);

/**
 * Frees a LibtsValue. NULL-safe.
 * For handle values, also releases the engine-side handle.
 */
void taiyaki_value_free(struct LibtsValue *val);

/**
 * Creates an f64 value.
 */
struct LibtsValue *taiyaki_value_number(double n);

/**
 * Creates a string value. `s` is a UTF-8 string of length `len`.
 */
struct LibtsValue *taiyaki_value_string(const char *s, uintptr_t len);

/**
 * Creates a boolean value. 0 maps to false, anything else to true.
 */
struct LibtsValue *taiyaki_value_bool(int32_t b);

/**
 * Creates a null value.
 */
struct LibtsValue *taiyaki_value_null(void);

/**
 * Creates an undefined value.
 */
struct LibtsValue *taiyaki_value_undefined(void);

/**
 * Creates an empty JS object.
 */
struct LibtsValue *taiyaki_object_new(struct LibtsRuntime *rt);

/**
 * Sets a property on an object. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_object_set(struct LibtsRuntime *rt,
                           const struct LibtsValue *obj,
                           const char *key,
                           uintptr_t key_len,
                           const struct LibtsValue *val);

/**
 * Gets a property from an object.
 */
struct LibtsValue *taiyaki_object_get(struct LibtsRuntime *rt,
                                      const struct LibtsValue *obj,
                                      const char *key,
                                      uintptr_t key_len);

/**
 * Creates an empty JS array.
 */
struct LibtsValue *taiyaki_array_new(struct LibtsRuntime *rt);

/**
 * Pushes an element onto an array. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_array_push(struct LibtsRuntime *rt,
                           const struct LibtsValue *arr,
                           const struct LibtsValue *val);

/**
 * Gets an element from an array by index.
 */
struct LibtsValue *taiyaki_array_get(struct LibtsRuntime *rt,
                                     const struct LibtsValue *arr,
                                     uint32_t index);

/**
 * Returns the length of an array. Returns -1 on error.
 */
int32_t taiyaki_array_length(struct LibtsRuntime *rt, const struct LibtsValue *arr);

/**
 * Calls a JS function. `func` must be a FunctionHandle.
 */
struct LibtsValue *taiyaki_call(struct LibtsRuntime *rt,
                                const struct LibtsValue *func,
                                const struct LibtsValue *const *args,
                                uintptr_t argc);

/**
 * Serializes a handle value to a JSON string.
 * Returns a String-typed LibtsValue.
 */
struct LibtsValue *taiyaki_to_json(struct LibtsRuntime *rt, const struct LibtsValue *val);

/**
 * Parses a JSON string and returns a handle value.
 */
struct LibtsValue *taiyaki_from_json(struct LibtsRuntime *rt, const char *json, uintptr_t len);

/**
 * Registers a host function as a JS global. Returns 0 on success, -1 on error.
 * `name` is a UTF-8 string of length `name_len`.
 * `callback` is a C function pointer; `user_data` is passed through to the callback.
 */
int32_t taiyaki_register_fn(struct LibtsRuntime *rt,
                            const char *name,
                            uintptr_t name_len,
                            LibtsHostFn callback,
                            void *user_data);

/**
 * Sets the memory limit in bytes. 0 means unlimited.
 */
void taiyaki_set_memory_limit(struct LibtsRuntime *rt, uintptr_t bytes);

/**
 * Sets the maximum stack size in bytes.
 */
void taiyaki_set_max_stack_size(struct LibtsRuntime *rt, uintptr_t bytes);

/**
 * Sets an execution timeout in milliseconds. Uses the interrupt handler.
 */
void taiyaki_set_execution_timeout(struct LibtsRuntime *rt, uint64_t milliseconds);

/**
 * Returns memory usage statistics. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_memory_usage(struct LibtsRuntime *rt, struct taiyaki_memory_stats *out);

/**
 * Triggers garbage collection.
 */
void taiyaki_run_gc(struct LibtsRuntime *rt);

/**
 * Evaluates JavaScript code as an ES module.
 * Returns an ObjectHandle to the module namespace (exports).
 * `code` is a UTF-8 string of length `code_len`.
 * `name` is a UTF-8 module name of length `name_len`.
 */
struct LibtsValue *taiyaki_eval_module(struct LibtsRuntime *rt,
                                       const char *code,
                                       uintptr_t code_len,
                                       const char *name,
                                       uintptr_t name_len);

/**
 * Evaluates TypeScript code as an ES module (strips types first).
 */
struct LibtsValue *taiyaki_eval_module_ts(struct LibtsRuntime *rt,
                                          const char *code,
                                          uintptr_t code_len,
                                          const char *name,
                                          uintptr_t name_len);

/**
 * Registers a module source for later import. Returns 0 on success, -1 on error.
 */
int32_t taiyaki_register_module(struct LibtsRuntime *rt,
                                const char *name,
                                uintptr_t name_len,
                                const char *code,
                                uintptr_t code_len);

/**
 * Gets a global property by name. Returns NULL on error.
 */
struct LibtsValue *taiyaki_get_global(struct LibtsRuntime *rt,
                                      const char *name,
                                      uintptr_t name_len);

/**
 * Calls a global function by name. Convenience for get_global + call.
 */
struct LibtsValue *taiyaki_call_global(struct LibtsRuntime *rt,
                                       const char *name,
                                       uintptr_t name_len,
                                       const struct LibtsValue *const *args,
                                       uintptr_t argc);

/**
 * Calls a function handle with f64 args, returns f64 result.
 * Avoids heap-allocating LibtsValue for each argument.
 */
double taiyaki_call_fast_f64(struct LibtsRuntime *rt,
                             const struct LibtsValue *func,
                             const double *args,
                             uintptr_t argc);

/**
 * Registers a native function that takes f64 args and returns f64.
 * Avoids LibtsValue boxing overhead for numeric functions.
 */
int32_t taiyaki_register_fast_fn_f64(struct LibtsRuntime *rt,
                                     const char *name,
                                     uintptr_t name_len,
                                     TaiyakiFastFnF64 callback,
                                     uintptr_t declared_argc,
                                     void *user_data);

#endif  /* TAIYAKI_H */
